"""empty message

Revision ID: 6801a322bf8e
Revises: 
Create Date: 2022-11-16 21:51:09.965255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6801a322bf8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('neptun', sa.String(length=6), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('neptun')
    )
    op.create_table('subject',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_neptun', sa.String(length=6), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['student_neptun'], ['student.neptun'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=6), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['student.neptun'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_neptun', sa.String(length=6), nullable=False),
    sa.Column('subject_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_neptun'], ['student.neptun'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('neptun1', sa.String(length=6), nullable=False),
    sa.Column('neptun2', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['neptun1'], ['student.neptun'], ),
    sa.ForeignKeyConstraint(['neptun2'], ['student.neptun'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutoring',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tutor_neptun', sa.String(length=6), nullable=False),
    sa.Column('tutoring_name', sa.String(length=255), nullable=False),
    sa.Column('subject_id', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['tutor_neptun'], ['student.neptun'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_member_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['group_member_id'], ['group_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutoring_participant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_neptun', sa.String(length=6), nullable=False),
    sa.Column('tutoring_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_neptun'], ['student.neptun'], ),
    sa.ForeignKeyConstraint(['tutoring_id'], ['tutoring.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutoring_participant')
    op.drop_table('group_post')
    op.drop_table('tutoring')
    op.drop_table('relations')
    op.drop_table('post')
    op.drop_table('group_requests')
    op.drop_table('group_member')
    op.drop_table('subject')
    op.drop_table('student')
    op.drop_table('group')
    # ### end Alembic commands ###
