"""Team size column added to Group

Revision ID: 722060525bf8
Revises: 6801a322bf8e
Create Date: 2022-11-24 11:52:05.429599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722060525bf8'
down_revision = '6801a322bf8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('relation', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=6), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('creationtime', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['relation'], ['relations.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['student.neptun'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_size', sa.Integer(), nullable=False))

    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_buddies', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.drop_column('is_buddies')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('team_size')

    op.drop_table('message')
    # ### end Alembic commands ###
